---
title: "Untitled"
author: "André"
date: "2023-07-20"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(lubridate)
library(shiny)
library(scales)

```



```{r}

dados_juros = read_rds("dados-preparados/dados_juros.rds")


dados_preco = read_rds("dados-preparados/dados_preco.rds")


dados_receita = read_rds("dados-preparados/dados_receita.rds") %>% 
    filter(receita != 0) %>% 
    filter(
        !str_detect(ticker, "BRAP4")
    ) %>% 
    filter(
        !str_detect(ticker, "BRAP3")
    ) %>% 
    mutate(
        prefixo = str_extract(ticker, "(^.+?) ", group = 1)
    )
    



data_inicial <- lubridate::floor_date(min(dados_receita$datas), "month")

data_final <- lubridate::floor_date(max(dados_receita$datas), "month")


datas_analise <- tibble(
    data = seq.Date(data_inicial, data_final, by = "day")
    ) %>% 
    cross_join(
        dados_receita %>% select(ticker) %>%  distinct()
    )


datas_analise_preco <- tibble(
    data = seq.Date(data_inicial, data_final, by = "day")
    ) %>% 
    cross_join(
        dados_receita %>% select(prefixo) %>%  distinct()
    )



dados_preco_completos = dados_preco %>% 
    right_join(
        datas_analise_preco,
        by = join_by(
            date == data,
            prefixo == prefixo
        )
    ) %>% 
    arrange(date) %>% 
    group_by(prefixo) %>% 
    fill(
        preco,
        .direction = "down"
    ) %>% 
    fill(
        mkt_cap,
        .direction = "down"
    ) %>% 
    ungroup() %>% 
    mutate(
        retorno_preco = preco /lag(preco) - 1 ,
        .by = prefixo
    )
    

    
    
dados_receita_completos <- dados_receita %>% 
    right_join(
        datas_analise,
        by = join_by(
            datas == data,
            ticker == ticker
        )
    ) %>% 
    mutate(
        data_referencia = make_date(year(datas) + 1, 12 ,31)
    ) %>% 
    arrange(datas) %>% 
    group_by(ticker) %>% 
    fill(
        receita,
        .direction = "down"
    ) %>% 
    ungroup() %>% 
    arrange(datas) %>% 
    mutate(
        crescimento_receita = receita / lag(receita) - 1,
        .by = c(ticker)
    ) %>% 
    replace_na(
        list(crescimento_receita = 0)
    ) %>% 
    mutate(
        indice_receita = cumprod(1 + crescimento_receita),
        .by = ticker
    ) %>% 
    mutate(
        prefixo = str_extract(ticker, "(^.+?) ", group = 1)
    )





receita_equal <- dados_receita_completos %>% 
    summarise(
        crescimento_receita = mean(crescimento_receita),
        .by = datas
    ) %>% 
    mutate(
        indice_receitas = cumprod(1 + crescimento_receita)
    )


receita_ponderada <- dados_receita_completos %>% 
    summarise(
        crescimento_receita = weighted.mean(crescimento_receita, receita),
        .by = datas
    ) %>% 
    mutate(
        indice_receitas = cumprod(1 + crescimento_receita)
    )



monta_indice_real <- function(
        data_inicio_ciclo = 2002, 
        data_fim_ciclo = 2006, 
        inicio_impacto = 0.5, #em relação ao tamanho do ciclo
        final_impacto_meses = 12
){

    datas_no_ciclo <- tibble(
        data = seq(make_date(data_inicio_ciclo,1,1), make_date(data_fim_ciclo,1,1), by = "month" )
    ) %>% 
        slice_tail(prop = 0.5)
    
    datas_impacto = tibble(
        data = seq(
            datas_no_ciclo$data %>% last() %>% lubridate::add_with_rollback(months(1)), 
            length.out = final_impacto_meses,
            by = "month"
        ) 
    )


}



```





```{r}


inputPanel(
    
  selectInput(
      inputId = "ticker", 
      label = "Ticker:",
      multiple = FALSE,
      choices = dados_receita$ticker %>%  unique() %>%  sort()
    )
  
)



receita_filtrada = reactive({
   
    dados_receita_completos %>% 
        filter(ticker %in% input$ticker )
}) 


renderPlot({
    
 
    ggplot(receita_filtrada()) +
        geom_line(
            aes(
                x = datas,
                y = indice_receita
            )
        )
       
    
})



```


```{r}


renderPlot({
    
 
    ggplot(receita_equal) +
        ggtitle("receita equal") +
        geom_line(
            aes(
                x = datas,
                y = indice_receitas
            )
        )
       
    
})




```



```{r}


renderPlot({
    
 
    ggplot(receita_ponderada) +
        ggtitle("receita ponderada") +
        geom_line(
            aes(
                x = datas,
                y = indice_receitas
            )
        )
       
    
})




```






```{r}


ciclos <- tribble(
    ~ciclo,           ~data_inicio, ~data_fim,
    "2002 - 2006"    , make_date(2002,1,1), make_date(2006,12,31),
    "2011 - 2012"    , make_date(2011,8,1), make_date(2012,3,16),
    "2016 - 2018"    , make_date(2016,1,1), make_date(2018,12,28)
    
)




#2002 - 2006 - ondee começa os dados
#1/8/2011 - 16/3/2012
#1/1/2016 - 28/12/2018

min(dados_receita$datas)


inputPanel(
    
  selectInput(
      inputId = "ciclo", 
      label = "Ciclo:",
      multiple = FALSE,
      choices = ciclos$ciclo
    ),
  
  # radioButtons(
  #     inputId = "tipo_ponderacao",
  #     label = "Tipo de Ponderação",
  #     choices = c("Equal", "MarketCap")  
  # )
  
  
)



renderPlot({

    
    input_ciclo = input$ciclo
    input_tipo_ponderacao = "Equal"
    
    ciclo_escolhido <- ciclos %>% 
        filter(
            ciclo == input_ciclo
        )
    
    dados_juros_grafico = dados_juros %>% 
        filter(
            data_analise >= ciclo_escolhido$data_inicio,
            data_analise <= ciclo_escolhido$data_fim
        )
    

    dados_receita_completos_grafico = dados_preco_completos %>%  select(prefixo, preco, retorno_preco, mkt_cap, date ) %>% 
        filter(
            date >= ciclo_escolhido$data_inicio,
            date <= ciclo_escolhido$data_fim
        ) %>%
        left_join(
            dados_receita_completos,
            by = join_by(
                prefixo == prefixo,
                date == datas
            )
        ) %>%
        rename(
            datas = date
        ) %>% 
        filter(
            !is.na(mkt_cap), !is.na(preco)
        ) %>% 
        mutate(
            tipo_ponderacao = input_tipo_ponderacao
        ) %>% 
        mutate(
            ponderacao = if_else(tipo_ponderacao == "Equal", 1, mkt_cap)
        ) %>% 
        replace_na(
            list(retorno_preco = 0)
        ) %>% 
        summarise(
            crescimento_receita = weighted.mean(x = crescimento_receita, w = ponderacao, na.rm = TRUE),
            retorno_preco = weighted.mean(x = retorno_preco, w = ponderacao, na.rm = TRUE),
            
            .by = datas
        ) %>% 
        arrange(datas) %>% 
        mutate(
            indice_precos = cumprod(1 + retorno_preco),
            indice_receitas = cumprod(1 + crescimento_receita)
        ) %>% 
        left_join(
            dados_juros_grafico %>% select(data_analise, di_4y, ntnb_4y),
            by = join_by(datas == data_analise)
        ) %>% 
        fill(
            di_4y,
            ntnb_4y,
            .direction = "down"
        ) %>% 
        mutate(
            datas = as.Date(datas)
        ) %>%             
        mutate(
            dias_inicio = (datas - min(datas)) %>%  as.integer()
        ) 

        
    
    
    

    scaling_factor <- 13 / 1.2
    
    
    grafico <- ggplot(
        dados_receita_completos_grafico,
        aes(x = datas %>%  as.Date())) +
        geom_line(
            aes(
                y = di_4y / scaling_factor,
                color = "DI 4y"
            ),
            linetype = "dashed",
            size = 1,
            show.legend = TRUE
        ) +
        geom_line(
            aes(
                y = indice_precos,
                color = "Índice Preços"
            ),
            size = 1,
            show.legend = TRUE
            
        ) +
        geom_line(
            aes(
                y = indice_receitas,
                color = "Índice Receitas"    
            ),
            size = 1,
            show.legend = TRUE
        ) +
        scale_color_manual(
            values = c(
                "Índice Preços" = "blue",
                "Índice Receitas" = "green",
                "DI 4y" = "darkred"
            )                
        ) + 
        scale_y_continuous(
            "Preços/Receitas",
            sec.axis = sec_axis(~. * scaling_factor, name = "DI 4y")
        ) +
        scale_x_date(
            
            labels = date_format("%m/%y"),
            breaks = date_breaks(width = "1 month"),
            sec.axis = sec_axis(
                trans = identity,
                breaks = date_breaks(width = "1 month"),
                labels = date_format("%m/%y")
            )
        ) +
        geom_hline(
            yintercept = 1,
            linewidth = 1
        ) +
        labs(
            x = "Data",
            color = "Série"
        ) +
        theme_minimal() +
        theme(
            legend.position = "top"
        )
        
    grafico
    
})



```





